mutation_mode: "categorized"  # "individual" or "categorized"
mutation_categories: [POR, VOR, ROR, DOR, NOR, AOR, SOR]  # Categories

mutations:
- category: POR
  file_type: provider
  mutation_type: provider_aws_to_google
  file_path: providers.tf
  patterns:
  - pattern: provider "aws"
    replacement: provider "google"
  id: 0_provider_aws_to_google_POR

- category: VOR
  file_type: provider
  mutation_type: region_us_east_to_eu_west
  file_path: providers.tf
  patterns:
  - pattern: region = "us-east-1"
    replacement: region = "eu-west-1"
  id: 2_region_us_east_to_eu_west_VOR


- category: DOR
  file_type: dependency
  mutation_type: remove_depends_on
  file_path: data.tf
  patterns:
  - pattern: 'depends_on = '
    replacement: '# depends_on removed'
  id: 4_remove_depends_on_DOR


- category: VOR
  file_type: configuration
  mutation_type: extreme_count_value
  file_path: vars.tf
  patterns:
  - pattern: count = 1
    replacement: count = 1000
  id: 6_extreme_count_value_VOR


- category: DOR
  file_type: dependency
  mutation_type: duplicate_dependency
  file_path: data.tf
  patterns:
  - pattern: depends_on = [ aws_lambda_function.lambda_reports]
    replacement: depends_on = [aws_security_group.example, aws_security_group.example]
  id: 9_duplicate_dependency_DOR

- category: DOR
  file_type: dependency
  mutation_type: remove_critical_dependency
  file_path: data.tf
  patterns:
  - pattern: depends_on = [aws_lambda_function.lambda_reports]
    replacement: '# depends_on removed'
  id: 10_remove_critical_dependency_DOR


- category: AOR
  file_type: provider
  mutation_type: invalid_authentication
  file_path: providers.tf
  patterns:
  - pattern: profile = "default"
    replacement: profile = "invalid_account"
  id: 13_invalid_authentication_AOR

- category: DOR
  file_type: dependency
  mutation_type: remove_implicit_dependency
  file_path: data.tf
  patterns:
  - pattern: depends_on = [aws_db_instance.example]
    replacement: '# depends_on removed'
  id: 16_remove_implicit_dependency_DOR


- category: POR
  file_type: provider
  mutation_type: provider_incompatibility
  file_path: providers.tf
  patterns:
  - pattern: provider "aws"
    replacement: provider "google"
  id: 18_provider_incompatibility_POR



